name: Cache Measures Nightly
on:
  push:
    branches: main
  # schedule:
  # - cron: "0 0 * * *"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Measures
        run: |
          wget ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar -O WSRT_Measures.ztar
          tar zxvf WSRT_Measures.ztar
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          body: |
            Ephemerides and geodetic data for casacore measures (via Astron) as of ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false


